#:schema node_modules/wrangler/config-schema.json
name = "docker"
main = "_worker.js"
compatibility_date = "2025-02-20"
compatibility_flags = ["nodejs_compat"]

routes = [
    { pattern = "docker.siki.moe", custom_domain = true },
    { pattern = "gcr.siki.moe", custom_domain = true },
    { pattern = "ghcr.siki.moe", custom_domain = true },
    { pattern = "k8s.siki.moe", custom_domain = true },
    { pattern = "lscr.siki.moe", custom_domain = true },
    { pattern = "nvcr.siki.moe", custom_domain = true },
    { pattern = "quay.siki.moe", custom_domain = true },
]

[observability]
enabled = true

[placement]
mode = "smart"
